"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(kr9*ctjegu0+8iw0-^%vna-p+@q(8!bf(4^6h_e2-@e&9u%!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# AUTH_USER_MODEL = "users.User"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'users',
    'course',
    'problems',
    'contests',
    'quizzes',
    'common',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD', '12345')
MYSQL_ROOT_PASSWORD = os.getenv('MYSQL_ROOT_PASSWORD', '12345')
MAIN_DB_NAME = os.getenv('MAIN_DB_NAME', 'finalproject')
DJANGO_DB_HOST = os.getenv('DJANGO_DB_HOST', 'localhost')
DJANGO_DB_PORT = os.getenv('DJANGO_DB_PORT', '3306')
DOMJUDGE_DB_HOST = os.getenv('DOMJUDGE_DB_HOST', 'localhost')
DOMJUDGE_DB_PORT = os.getenv('DOMJUDGE_DB_PORT', '13306')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MAIN_DB_NAME,       
        'USER': 'root',        
        'PASSWORD': MYSQL_ROOT_PASSWORD, 
        'HOST': DJANGO_DB_HOST,   
        'PORT': DJANGO_DB_PORT,       
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'domjudge': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'domjudge',
        'USER': 'domjudge',
        'PASSWORD': MYSQL_PASSWORD,
        'HOST': DOMJUDGE_DB_HOST,
        'PORT': DOMJUDGE_DB_PORT,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    'ROTATE_REFRESH_TOKENS': False,           
    'BLACKLIST_AFTER_ROTATION': False,        
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"  

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

DOMJUDGE_API_URL = os.getenv('DOMJUDGE_API_URL', 'http://localhost:8080/api/v4')
DOMJUDGE_USERNAME = os.getenv('DOMJUDGE_USERNAME', 'admin')
DOMJUDGE_PASSWORD = os.getenv('DOMJUDGE_PASSWORD', '12345')

# VNPay Configuration
VNPAY_TMN_CODE = os.getenv('VNPAY_TMN_CODE', '')  # Mã website tại VNPay
VNPAY_HASH_SECRET = os.getenv('VNPAY_HASH_SECRET', '')  # Secret key
VNPAY_URL = os.getenv('VNPAY_URL', 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html')  # URL thanh toán VNPay
VNPAY_RETURN_URL = os.getenv('VNPAY_RETURN_URL', 'https://josephine-unsurmising-importantly.ngrok-free.dev/api/payment/vnpay/return/')  # URL callback từ VNPay
VNPAY_API_URL = os.getenv('VNPAY_API_URL', 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction')  # URL API VNPay

# ==========================================
# DJANGO-Q2 CONFIGURATION
# ==========================================
Q_CLUSTER = {
    'name': 'recommendation_cluster',
    'workers': 2,
    'recycle': 500,
    'timeout': 3600,  # 1 hour timeout for training
    'retry': 3660,  # retry must be > timeout (3600 + 60 seconds)
    'compress': True,
    'save_limit': 250,
    'queue_limit': 50,
    'label': 'Recommendation System',
    'orm': 'default',  # Use Django ORM instead of Redis
    'catch_up': False,  # Don't catch up on missed schedules
}